#!/usr/bin/env python3

import sys

def error():
    if len(sys.argv) == 1:
        exit (84)
    if sys.argv[1] == "-h" and len(sys.argv) == 2:
        usage()
    if len(sys.argv) % 2 != 1:
        exit (84)
    for z in range(1, len(sys.argv)):
        for i in range(0, len(sys.argv[z])):
            if ((sys.argv[z][i] < '/' or sys.argv[z][i] > ':') and sys.argv[z][i] != '*'):
                exit(84)

def usage():
        print('USAGE\n\t./107tranfer [num den]*')
        print('DESCRIPTION')
        print('\tnum\tpolynomial numerator defined by its coefficients')
        print('\tden\tpolynomial denominator defined by its coefficients')
        exit (0)

if __name__ == '__main__':
    error()
