#!/usr/bin/env python3
import sys
import math

def header():
    print('USAGE\n\t./108trigo fun a0 a1 a2 ...\n')
    print('DESCRIPTION\n\tfun\tfunction to be applied, among at least "EXP", "COS", "SIN", "COSH"')
    print('\t\tand "SINH"')
    print('\tai\tcoeficients of the matrix')
    exit(0)

def checkarg():
    tab = [0] * (len(sys.argv) - 2)
    j = 0
    if (len(sys.argv) < 3):
        if (len(sys.argv) == 2 and sys.argv[1] == '-h'):
            header()
        exit(84)
    if sys.argv[1] != 'COS' and sys.argv[1] != 'SIN' and sys.argv[1] != 'COSH' and sys.argv[1] != 'SINH' and sys.argv[1] != 'EXP':
        exit(84)
    for i in range (2, len(sys.argv)):
        try:
            tab[j] = (int)(sys.argv[i])
        except ValueError:
            exit(84)
        j += 1
    return (tab)

def main():
    tab = checkarg()


if __name__ == "__main__":
    main()
