version: '3'
services:
    poll:
        build: .
        ports:
            - "5000:80"
        networks:
            - poll-tier
    redis:
        image: redis:buster
        expose:
            - 6379
        networks:
            - poll-tier
            - back-tier
    worker:
        build: .
        networks:
            - back-tier
    db:
        image: postgres:latest
        networks:
            - result-tier
            - back-tier
    result:
        build: .
        ports:
            - "5001:80"
        networks:
            - result-tier
networks:
    poll-tier:
        driver: "bridge"
    result-tier:
        driver: "bridge"
    back-tier:
        driver: "bridge"