#!/usr/bin/env python3
import sys
import math
from math import sqrt

def header():
    print('USAGE\n\t./108trigo fun a0 a1 a2 ...\n')
    print('DESCRIPTION\n\tfun\tfunction to be applied, among at least "EXP", "COS", "SIN", "COSH"')
    print('\t\tand "SINH"')
    print('\tai\tcoeficients of the matrix')
    exit(0)

def arg_nbr():
    if (len(sys.argv) < 3):
        if (len(sys.argv) == 2 and sys.argv[1] == '-h'):
            header()
        exit(84)
    if (sqrt(len(sys.argv) - 2).is_integer() == False):
        exit(84)
    if sys.argv[1] != 'COS' and sys.argv[1] != 'SIN' and sys.argv[1] != 'COSH' and sys.argv[1] != 'SINH' and sys.argv[1] != 'EXP':
        exit(84)

def checkarg():
    tab = [0] * (len(sys.argv) - 2)
    j = 0
    for i in range (2, len(sys.argv)):
        try:
            tab[j] = (int)(sys.argv[i])
        except ValueError:
            exit(84)
        j += 1
    return (tab)

def doubletab(tab):
    n  = (int)(sqrt(len(tab)))
    j = 0
    dbltab = [0] * n
    for i in range(0, len(tab), n):
        dbltab[j] = tab[i:i+n]
        j += 1
    return(dbltab)

def main():
    arg_nbr()
    tab = checkarg()
    dbltab = doubletab(tab)

if __name__ == "__main__":
    main()
